version: "3.3"
volumes:
  data:
services:
  db:
    image: mysql:${MYSQL_VER}
    ports:
      - "3000:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE:${MYSQL_DATABASE}    
  admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
  app:
    build: .
    ports:
      - 8080:80
    volumes:
      - /home/nathan/php:/var/www/html/
    links:
      - db